document.addEventListener('DOMContentLoaded', () => {
    const formulas = [
        { name: 'Area of a Circle', content: 'A = πr<sup>2</sup>' },
        { name: 'Area of a Rectangle', content: 'A = lw' },
        { name: 'Area of a Triangle', content: 'A = 0.5bh' },
        { name: 'Binomial Theorem', content: '(a + b)<sup>n</sup> = ∑<sub>k=0</sub><sup>n</sup> C(n,k)a<sup>n-k</sup>b<sup>k</sup>' },
        { name: 'Circumference of a Circle', content: 'C = 2πr' },
        { name: 'Combinations', content: 'C(n,r) = n! / [r!(n - r)!]' },
        { name: 'Cosine Rule', content: 'c<sup>2</sup> = a<sup>2</sup> + b<sup>2</sup> - 2ab cos(C)' },
        { name: 'Derivative of a Constant', content: 'd/dx[c] = 0' },
        { name: 'Derivative of a Function', content: 'd/dx[f(x)] = f\'(x)' },
        { name: 'Derivative of a Sum', content: 'd/dx[u + v] = du/dx + dv/dx' },
        { name: 'Distance Formula', content: 'd = √[(x<sub>2</sub> - x<sub>1</sub>)<sup>2</sup> + (y<sub>2</sub> - y<sub>1</sub>)<sup>2</sup>]' },
        { name: 'Euler\'s Formula', content: 'e<sup>ix</sup> = cos(x) + i sin(x)' },
        { name: 'Exponential Growth', content: 'P(t) = P<sub>0</sub>e<sup>rt</sup>' },
        { name: 'Factorial', content: 'n! = n × (n-1) × (n-2) × ... × 1' },
        { name: 'FOIL Method', content: '(a + b)(c + d) = ac + ad + bc + bd' },
        { name: 'Geometric Series Sum', content: 'S<sub>n</sub> = a(1 - r<sup>n</sup>) / (1 - r)' },
        { name: 'Harmonic Mean', content: 'HM = n / (∑<sub>i=1</sub><sup>n</sup> 1/x<sub>i</sub>)' },
        { name: 'Law of Sines', content: 'a/sin(A) = b/sin(B) = c/sin(C)' },
        { name: 'Logarithm Change of Base', content: 'log<sub>b</sub>(a) = log<sub>c</sub>(a) / log<sub>c</sub>(b)' },
        { name: 'Logarithm Power Rule', content: 'log<sub>b</sub>(x<sup>y</sup>) = y log<sub>b</sub>(x)' },
        { name: 'Logarithm Product Rule', content: 'log<sub>b</sub>(xy) = log<sub>b</sub>(x) + log<sub>b</sub>(y)' },
        { name: 'Logarithm Quotient Rule', content: 'log<sub>b</sub>(x/y) = log<sub>b</sub>(x) - log<sub>b</sub>(y)' },
        { name: 'Mean', content: 'μ = (∑<sub>i=1</sub><sup>n</sup> x<sub>i</sub>) / n' },
        { name: 'Median', content: 'Middle value when data is ordered' },
        { name: 'Midpoint Formula', content: 'M = [(x<sub>1</sub> + x<sub>2</sub>) / 2, (y<sub>1</sub> + y<sub>2</sub>) / 2]' },
        { name: 'Mode', content: 'Most frequently occurring value' },
        { name: 'Newton\'s Method', content: 'x<sub>n+1</sub> = x<sub>n</sub> - f(x<sub>n</sub>) / f\'(x<sub>n</sub>)' },
        { name: 'Permutation', content: 'P(n,r) = n! / (n - r)!' },
        { name: 'Pythagorean Theorem', content: 'a<sup>2</sup> + b<sup>2</sup> = c<sup>2</sup>' },
        { name: 'Quadratic Formula', content: 'ax<sup>2</sup> + bx + c = 0, x = (-b ± √(b<sup>2</sup> - 4ac)) / 2a' },
        { name: 'Radian to Degree Conversion', content: 'Degrees = Radians × (180/π)' },
        { name: 'Simple Interest', content: 'I = Prt' },
        { name: 'Slope Formula', content: 'm = (y<sub>2</sub> - y<sub>1</sub>) / (x<sub>2</sub> - x<sub>1</sub>)' },
        { name: 'Slope-Intercept Form', content: 'y = mx + b' },
        { name: 'Standard Deviation', content: 'σ = √[(1/n)∑<sub>i=1</sub><sup>n</sup>(x<sub>i</sub> - μ)<sup>2</sup>]' },
        { name: 'Sum of First n Natural Numbers', content: 'S = n(n + 1) / 2' },
        { name: 'Sum of First n Odd Numbers', content: 'S = n<sup>2</sup>' },
        { name: 'Sum of Interior Angles of a Polygon', content: 'Sum = (n - 2)180°' },
        { name: 'Surface Area of a Cube', content: 'SA = 6a<sup>2</sup>' },
        { name: 'Surface Area of a Sphere', content: 'SA = 4πr<sup>2</sup>' },
        { name: 'Tangent Line', content: 'y - y<sub>1</sub> = m(x - x<sub>1</sub>)' },
        { name: 'Volume of a Cube', content: 'V = a<sup>3</sup>' },
        { name: 'Volume of a Cylinder', content: 'V = πr<sup>2</sup>h' },
        { name: 'Volume of a Rectangular Prism', content: 'V = lwh' },
        { name: 'Volume of a Sphere', content: 'V = 4/3 πr<sup>3</sup>' },
        { name: 'Weighted Average', content: 'Weighted Average = (∑w<sub>i</sub>x<sub>i</sub>) / (∑w<sub>i</sub>)' },
        { name: 'Zero Product Property', content: 'If ab = 0, then a = 0 or b = 0' },
        // Adding more formulas to make it 100 in total
        { name: 'Absolute Value', content: '|x| = x if x ≥ 0, -x if x < 0' },
        { name: 'Addition of Matrices', content: 'A + B = [a<sub>ij</sub> + b<sub>ij</sub>]' },
        { name: 'Angle Sum of a Triangle', content: 'Sum = 180°' },
        { name: 'Arc Length', content: 'L = rθ' },
        { name: 'Area of an Ellipse', content: 'A = πab' },
        { name: 'Area of a Parallelogram', content: 'A = bh' },
        { name: 'Area of a Rhombus', content: 'A = 0.5d<sub>1</sub>d<sub>2</sub>' },
        { name: 'Binomial Coefficient', content: 'C(n, k) = n! / [k!(n - k)!]' },
        { name: 'Cartesian to Polar Coordinates', content: 'r = √(x<sup>2</sup> + y<sup>2</sup>), θ = tan<sup>-1</sup>(y/x)' },
        { name: 'Cauchy-Schwarz Inequality', content: '|⟨u, v⟩| ≤ ||u|| ||v||' },
        { name: 'Celsius to Fahrenheit', content: 'F = C × 9/5 + 32' },
        { name: 'Addition of Fractions', content: 'a/b + c/d = (ad + bc) / bd' },
        { name: 'Angle Sum of Polygon', content: 'Sum = (n - 2) × 180°' },
        { name: 'Arccosine', content: 'y = arccos(x)' },
        { name: 'Arcsine', content: 'y = arcsin(x)' },
        { name: 'Arctangent', content: 'y = arctan(x)' },
        { name: 'Area of a Sector', content: 'A = 0.5r<sup>2</sup>θ' },
        { name: 'Area of a Trapezoid', content: 'A = 0.5(a + b)h' },
        { name: 'Average Rate of Change', content: 'ARC = [f(b) - f(a)] / (b - a)' },
        { name: 'Bernoulli\'s Equation', content: 'P + 0.5ρv<sup>2</sup> + ρgh = constant' },
        { name: 'Binomial Probability', content: 'P(X = k) = C(n, k)p<sup>k</sup>(1 - p)<sup>n - k</sup>' },
        { name: 'Cardano\'s Formula', content: 'x = cube root(d/a) + cube root(b/a)' },
        { name: 'Cauchy-Riemann Equations', content: 'u<sub>x</sub> = v<sub>y</sub>, u<sub>y</sub> = -v<sub>x</sub>' },
        { name: 'Chain Rule', content: 'dy/dx = (dy/du)(du/dx)' },
        { name: 'Characteristic Equation', content: 'det(A - λI) = 0' },
        { name: 'Chebyshev\'s Inequality', content: 'P(|X - μ| ≥ kσ) ≤ 1/k<sup>2</sup>' },
        { name: 'Chi-Square Test Statistic', content: 'χ<sup>2</sup> = ∑(O - E)<sup>2</sup> / E' },
        { name: 'Complementary Angles', content: 'A + B = 90°' },
        { name: 'Complete the Square', content: 'ax<sup>2</sup> + bx + c = a(x + b/2a)<sup>2</sup> - (b<sup>2</sup> - 4ac)/4a' },
        { name: 'Cosecant', content: 'csc(θ) = 1/sin(θ)' },
        { name: 'Cosine Addition Formula', content: 'cos(a + b) = cos(a)cos(b) - sin(a)sin(b)' },
        { name: 'Cosine Subtraction Formula', content: 'cos(a - b) = cos(a)cos(b) + sin(a)sin(b)' },
        { name: 'Cotangent', content: 'cot(θ) = 1/tan(θ)' },
        { name: 'Covariance', content: 'cov(X,Y) = E[(X - μ<sub>X</sub>)(Y - μ<sub>Y</sub>)]' },
        { name: 'Critical Points', content: 'f\'(x) = 0' },
        { name: 'Cubic Equation', content: 'ax<sup>3</sup> + bx<sup>2</sup> + cx + d = 0' },
        { name: 'Definite Integral', content: '∫<sub>a</sub><sup>b</sup> f(x) dx' },
        { name: 'Difference of Cubes', content: 'a<sup>3</sup> - b<sup>3</sup> = (a - b)(a<sup>2</sup> + ab + b<sup>2</sup>)' },
        { name: 'Difference of Squares', content: 'a<sup>2</sup> - b<sup>2</sup> = (a - b)(a + b)' },
        { name: 'Double Angle Formulas', content: 'sin(2θ) = 2sin(θ)cos(θ), cos(2θ) = cos<sup>2</sup>(θ) - sin<sup>2</sup>(θ)' },
        { name: 'Euler\'s Totient Function', content: 'φ(n) = n(1 - 1/p<sub>1</sub>)(1 - 1/p<sub>2</sub>)...(1 - 1/p<sub>k</sub>)' },
        { name: 'Expected Value', content: 'E(X) = ∑xP(x)' },
        { name: 'Factor by Grouping', content: 'ax + ay + bx + by = a(x + y) + b(x + y)' },
        { name: 'Fermat\'s Last Theorem', content: 'x<sup>n</sup> + y<sup>n</sup> = z<sup>n</sup> has no positive integer solutions for n > 2' },
        { name: 'Geometric Mean', content: 'GM = (x<sub>1</sub>x<sub>2</sub>...x<sub>n</sub>)<sup>1/n</sup>' },
        { name: 'Gram-Schmidt Process', content: 'u<sub>1</sub> = v<sub>1</sub>, u<sub>2</sub> = v<sub>2</sub> - proj<sub>u<sub>1</sub></sub>(v<sub>2</sub>)' },
        { name: 'Half-Angle Formulas', content: 'sin(θ/2) = ±√[(1 - cos(θ))/2], cos(θ/2) = ±√[(1 + cos(θ))/2]' },
        { name: 'Harmonic Series', content: 'H<sub>n</sub> = 1 + 1/2 + 1/3 + ... + 1/n' },
        { name: 'Hyperbolic Cosine', content: 'cosh(x) = (e<sup>x</sup> + e<sup>-x</sup>) / 2' },
        { name: 'Hyperbolic Sine', content: 'sinh(x) = (e<sup>x</sup> - e<sup>-x</sup>) / 2' },
        { name: 'Implicative Normal Form', content: '(p → q) ≡ (¬p ∨ q)' },
        { name: 'Indefinite Integral', content: '∫ f(x) dx' },
        { name: 'Inverse Cosine', content: 'cos<sup>-1</sup>(x)' },
        { name: 'Inverse Sine', content: 'sin<sup>-1</sup>(x)' },
        { name: 'Inverse Tangent', content: 'tan<sup>-1</sup>(x)' },
        { name: 'Laplace Transform', content: 'L{f(t)} = ∫<sub>0</sub><sup>∞</sup> e<sup>-st</sup>f(t) dt' },
        { name: 'Law of Cosines', content: 'c<sup>2</sup> = a<sup>2</sup> + b<sup>2</sup> - 2ab cos(γ)' },
        { name: 'Law of Sines', content: 'a/sin(A) = b/sin(B) = c/sin(C)' },
        { name: 'Laws of Logarithms', content: 'log<sub>b</sub>(xy) = log<sub>b</sub>(x) + log<sub>b</sub>(y)' },
        { name: 'Limit Definition of a Derivative', content: 'f\'(x) = lim<sub>h→0</sub> [f(x + h) - f(x)] / h' },
        { name: 'Linear Combination', content: 'c<sub>1</sub>v<sub>1</sub> + c<sub>2</sub>v<sub>2</sub> + ... + c<sub>n</sub>v<sub>n</sub>' },
        { name: 'Linear Regression', content: 'y = a + bx' },
        { name: 'Logarithm Base Change', content: 'log<sub>b</sub>(x) = log<sub>a</sub>(x) / log<sub>a</sub>(b)' },
        { name: 'Logistic Growth Model', content: 'P(t) = K / (1 + Ae<sup>-Bt</sup>)' },
        { name: 'Matrix Addition', content: 'A + B = [a<sub>ij</sub> + b<sub>ij</sub>]' },
        { name: 'Matrix Multiplication', content: 'AB = [∑<sub>k</sub> a<sub>ik</sub>b<sub>kj</sub>]' },
        { name: 'Algebraic Identity', content: '(a + b)<sup>2</sup> = a<sup>2</sup> + 2ab + b<sup>2</sup>' },
        { name: 'Algebraic Identity', content: '(a - b)<sup>2</sup> = a<sup>2</sup> - 2ab + b<sup>2</sup>' },
        { name: 'Algebraic Identity', content: '(a + b)(a - b) = a<sup>2</sup> - b<sup>2</sup>' },
        { name: 'Amortization Formula', content: 'A = P r(1 + r)<sup>n</sup> / [(1 + r)<sup>n</sup> - 1]' },
        { name: 'Area of an Equilateral Triangle', content: 'A = (√3 / 4)a<sup>2</sup>' },
        { name: 'Arc Length of a Circle', content: 'L = rθ' },
        { name: 'Arccosine Function', content: 'y = arccos(x)' },
        { name: 'Arcsine Function', content: 'y = arcsin(x)' },
        { name: 'Arctangent Function', content: 'y = arctan(x)' },
        { name: 'Area of a Kite', content: 'A = (d<sub>1</sub> × d<sub>2</sub>) / 2' },
        { name: 'Area of an Annulus', content: 'A = π(R<sup>2</sup> - r<sup>2</sup>)' },
        { name: 'Area of a Regular Polygon', content: 'A = 0.25 n s<sup>2</sup> cot(π/n)' },
        { name: 'Bayes\' Theorem', content: 'P(A|B) = [P(B|A)P(A)] / P(B)' },
        { name: 'Bessel\'s Equation', content: 'x<sup>2</sup>y\'\' + xy\' + (x<sup>2</sup> - n<sup>2</sup>)y = 0' },
        { name: 'Binomial Distribution', content: 'P(X = k) = C(n, k)p<sup>k</sup>(1 - p)<sup>n - k</sup>' },
        { name: 'Black-Scholes Equation', content: '∂V/∂t + 0.5σ<sup>2</sup>S<sup>2</sup>∂<sup>2</sup>V/∂S<sup>2</sup> + rS∂V/∂S - rV = 0' },
        { name: 'Bode\'s Law', content: 'd = 0.4 + 0.3 × 2<sup>n</sup>' },
        { name: 'Bragg\'s Law', content: 'nλ = 2d sin θ' },
        { name: 'Center of Mass', content: 'x<sub>cm</sub> = (Σm<sub>i</sub>x<sub>i</sub>) / Σm<sub>i</sub>' },
        { name: 'Centripetal Force', content: 'F = m v<sup>2</sup> / r' },
        { name: 'Characteristic Polynomial', content: 'det(A - λI)' },
        { name: 'Clausius-Clapeyron Equation', content: 'dP/dT = L/T(ΔV)' },
        { name: 'Coefficient of Variation', content: 'CV = (σ / μ) × 100%' },
        { name: 'Commutative Property of Addition', content: 'a + b = b + a' },
        { name: 'Commutative Property of Multiplication', content: 'ab = ba' },
        { name: 'Complement Rule', content: 'P(A\') = 1 - P(A)' },
        { name: 'Compound Interest', content: 'A = P(1 + r/n)<sup>nt</sup>' },
        { name: 'Conservation of Energy', content: 'E = KE + PE' },
        { name: 'Continuity Equation', content: 'A<sub>1</sub>v<sub>1</sub> = A<sub>2</sub>v<sub>2</sub>' },
        { name: 'Critical Damping', content: 'ζ = 1' },
        { name: 'Cross Product', content: 'A × B = |A||B| sin θ n' },
        { name: 'De Moivre\'s Theorem', content: '(cos θ + i sin θ)<sup>n</sup> = cos(nθ) + i sin(nθ)' },
        { name: 'Degree to Radian Conversion', content: 'radians = degrees × π/180' },
        { name: 'Density', content: 'ρ = m / V' },
        { name: 'Derivative of Exponential Function', content: 'd/dx(e<sup>x</sup>) = e<sup>x</sup>' },
        { name: 'Derivative of Natural Logarithm', content: 'd/dx(ln(x)) = 1/x' },
        { name: 'Descriptive Statistics', content: 'X̄ = (Σx<sub>i</sub>) / n' },
        { name: 'Diagonal of a Square', content: 'd = a√2' },
        { name: 'Divisibility Rule for 3', content: 'Sum of digits is divisible by 3' },
        { name: 'Divisibility Rule for 9', content: 'Sum of digits is divisible by 9' },
        { name: 'Double Integral', content: '∬_D f(x, y) dA' },
        { name: 'Eigenvalue Equation', content: 'Av = λv' },
        { name: 'Electric Field', content: 'E = F / q' },
        { name: 'Euler\'s Identity', content: 'e<sup>iπ</sup> + 1 = 0' },
        { name: 'Euler\'s Theorem', content: 'a<sup>φ(n)</sup> ≡ 1 (mod n)' },
        { name: 'Fibonacci Sequence', content: 'F<sub>n</sub> = F<sub>n-1</sub> + F<sub>n-2</sub>' },
        { name: 'Gauss\'s Law', content: '∮E · dA = Q/ε<sub>0</sub>' },
        { name: 'Geometric Series', content: 'S<sub>n</sub> = a(1 - r<sup>n</sup>) / (1 - r)' },
        { name: 'Gravitational Force', content: 'F = G(m<sub>1</sub>m<sub>2</sub> / r<sup>2</sup>)' },
        { name: 'Heat Equation', content: '∂u/∂t = α∇<sup>2</sup>u' },
        { name: 'Hess\'s Law', content: 'ΔH = ΣΔH<sub>products</sub> - ΣΔH<sub>reactants</sub>' },
        { name: 'Ideal Gas Law', content: 'PV = nRT' },
        { name: 'Impulse', content: 'J = FΔt' },
        { name: 'Inverse Function', content: 'f(f<sup>-1</sup>(x)) = x' },
        { name: 'Kinetic Energy', content: 'KE = 0.5mv<sup>2</sup>' },
        { name: 'Kirchhoff\'s Voltage Law', content: 'ΣV = 0' },
        { name: 'Lagrange Interpolation', content: 'P(x) = Σ (y<sub>i</sub> L<sub>i</sub>(x))' },
        { name: 'Laplace\'s Equation', content: '∇<sup>2</sup>φ = 0' },
        { name: 'Law of Tangents', content: '(a - b) / (a + b) = tan[(A - B) / 2] / tan[(A + B) / 2]' },
        { name: 'Maclaurin Series', content: 'f(x) = Σ (f<sup>(n)</sup>(0) / n!) x<sup>n</sup>' },
        { name: 'Magnetic Field', content: 'B = μ<sub>0</sub>I / 2πr' },
        { name: 'Marginal Cost', content: 'MC = ΔTC / ΔQ' },
        { name: 'Angle of Elevation', content: 'tan(θ) = opposite / adjacent' },
        { name: 'Antiderivative', content: '∫ f(x) dx = F(x) + C' },
        { name: 'Area of a Parallelogram', content: 'A = b × h' },
        { name: 'Area of a Rhombus', content: 'A = (d<sub>1</sub> × d<sub>2</sub>) / 2' },
        { name: 'Area of an Ellipse', content: 'A = πab' },
        { name: 'Arithmetico-Geometric Series', content: 'S = a / (1 - r) + dr / (1 - r)<sup>2</sup>' },
        { name: 'Barycentric Coordinates', content: 'x = (x<sub>1</sub> + x<sub>2</sub> + x<sub>3</sub>) / 3' },
        { name: 'Basic Probability', content: 'P(A and B) = P(A)P(B)' },
        { name: 'Biot-Savart Law', content: 'dB = (μ<sub>0</sub> / 4π) (Idl × r) / r<sup>3</sup>' },
        { name: 'Box Volume', content: 'V = l × w × h' },
        { name: 'Cauchy-Schwarz Inequality', content: '|⟨x, y⟩| ≤ ||x|| ||y||' },
        { name: 'Characteristic Impedance', content: 'Z<sub>0</sub> = √(L/C)' },
        { name: 'Circle Equation', content: '(x - h)<sup>2</sup> + (y - k)<sup>2</sup> = r<sup>2</sup>' },
        { name: 'Commutative Property of Addition', content: 'a + b = b + a' },
        { name: 'Commutative Property of Multiplication', content: 'ab = ba' },
        { name: 'Compound Angle Formula', content: 'cos(a + b) = cos(a)cos(b) - sin(a)sin(b)' },
        { name: 'Cone Volume', content: 'V = (1/3)πr<sup>2</sup>h' },
        { name: 'Convex Combination', content: 'λ<sub>1</sub>x<sub>1</sub> + λ<sub>2</sub>x<sub>2</sub> + ... + λ<sub>n</sub>x<sub>n</sub>' },
        { name: 'Coriolis Force', content: 'F<sub>cor</sub> = 2m(v × Ω)' },
        { name: 'Cosine Rule', content: 'c<sup>2</sup> = a<sup>2</sup> + b<sup>2</sup> - 2ab cos(C)' },
        { name: 'Coulomb\'s Law', content: 'F = k (q<sub>1</sub>q<sub>2</sub>) / r<sup>2</sup>' },
        { name: 'Covariance Matrix', content: 'cov(X, Y) = Σ((X - μ<sub>X</sub>)(Y - μ<sub>Y</sub>)) / (n - 1)' },
        { name: 'Cylinder Surface Area', content: 'A = 2πr(r + h)' },
        { name: 'Differential Equation', content: 'dy/dx + P(x)y = Q(x)' },
        { name: 'Directional Derivative', content: 'D<sub>u</sub>f = ∇f · u' },
        { name: 'Discriminant', content: 'Δ = b<sup>2</sup> - 4ac' },
        { name: 'Divergence', content: '∇·F' },
        { name: 'Dot Product', content: 'A · B = |A||B| cos θ' },
        { name: 'Eigenvector', content: 'A - λI' },
        { name: 'Elastic Potential Energy', content: 'U = 0.5 k x<sup>2</sup>' },
        { name: 'Electric Potential', content: 'V = kq/r' },
        { name: 'Ellipse Equation', content: '(x<sup>2</sup>/a<sup>2</sup>) + (y<sup>2</sup>/b<sup>2</sup>) = 1' },
        { name: 'Empirical Rule', content: '68-95-99.7' },
        { name: 'Energy-Momentum Relation', content: 'E<sup>2</sup> = (pc)<sup>2</sup> + (m<sub>0</sub>c<sup>2</sup>)<sup>2</sup>' },
        { name: 'Euler\'s Formula (complex analysis)', content: 'e<sup>ix</sup> = cos(x) + i sin(x)' },
        { name: 'Exponential Decay', content: 'N(t) = N<sub>0</sub>e<sup>-λt</sup>' },
        { name: 'Fermat\'s Principle', content: 'δ ∫ n ds = 0' },
        { name: 'Fourier Transform', content: 'F(ω) = ∫ f(t)e<sup>-iωt</sup> dt' },
        { name: 'Frequency', content: 'f = 1/T' },
        { name: 'Fresnel Equations', content: 'r<sub>s</sub> = (n<sub>1</sub> cos θ<sub>i</sub> - n<sub>2</sub> cos θ<sub>t</sub>) / (n<sub>1</sub> cos θ<sub>i</sub> + n<sub>2</sub> cos θ<sub>t</sub>)' },
        { name: 'Frustum Volume', content: 'V = (1/3)πh(r<sub>1</sub><sup>2</sup> + r<sub>1</sub>r<sub>2</sub> + r<sub>2</sub><sup>2</sup>)' },
        { name: 'Gamma Function', content: 'Γ(n) = ∫<sub>0</sub><sup>∞</sup> t<sup>n-1</sup> e<sup>-t</sup> dt' },
        { name: 'Geometric Mean', content: 'GM = (x<sub>1</sub>x<sub>2</sub>...x<sub>n</sub>)<sup>1/n</sup>' },
        { name: 'Gradient', content: '∇f' },
        { name: 'Gravitational Potential Energy', content: 'U = mgh' },
        { name: 'Greatest Common Divisor', content: 'gcd(a, b)' },
        { name: 'Green\'s Theorem', content: '∮C F · dr = ∬D (∇ × F) · dA' },
        { name: 'Harmonic Mean', content: 'HM = n / (1/x<sub>1</sub> + 1/x<sub>2</sub> + ... + 1/x<sub>n</sub>)' },
        { name: 'Heaviside Step Function', content: 'H(x) = 0 for x < 0, H(x) = 1 for x ≥ 0' },
        { name: 'Hessian Matrix', content: 'H = ∂<sup>2</sup>f / ∂x<sub>i</sub>∂x<sub>j</sub>' },
        { name: 'Hyperbolic Cosine', content: 'cosh(x) = (e<sup>x</sup> + e<sup>-x</sup>) / 2' },
        { name: 'Hyperbolic Sine', content: 'sinh(x) = (e<sup>x</sup> - e<sup>-x</sup>) / 2' },
        { name: 'Hypergeometric Distribution', content: 'P(X = k) = [C(K, k) C(N - K, n - k)] / C(N, n)' },
        { name: 'Implicit Differentiation', content: 'dy/dx = - (∂F/∂x) / (∂F/∂y)' },
        { name: 'Inductive Step', content: 'P(k) → P(k + 1)' },
        { name: 'Integration by Parts', content: '∫ u dv = uv - ∫ v du' },
        { name: 'Inverse Function Theorem', content: 'if f is invertible, (f<sup>-1</sup>)\'(y) = 1 / f\'(x)' },
        { name: 'Isoperimetric Inequality', content: '4πA ≤ P<sup>2</sup>' },
        { name: 'Angle Addition Formula (Sine)', content: 'sin(a + b) = sin(a)cos(b) + cos(a)sin(b)' },
        { name: 'Angle Addition Formula (Cosine)', content: 'cos(a + b) = cos(a)cos(b) - sin(a)sin(b)' },
        { name: 'Angle Addition Formula (Tangent)', content: 'tan(a + b) = (tan(a) + tan(b)) / (1 - tan(a)tan(b))' },
        { name: 'Angle Subtraction Formula (Sine)', content: 'sin(a - b) = sin(a)cos(b) - cos(a)sin(b)' },
        { name: 'Angle Subtraction Formula (Cosine)', content: 'cos(a - b) = cos(a)cos(b) + sin(a)sin(b)' },
        { name: 'Angle Subtraction Formula (Tangent)', content: 'tan(a - b) = (tan(a) - tan(b)) / (1 + tan(a)tan(b))' },
        { name: 'Double Angle Formula (Sine)', content: 'sin(2a) = 2sin(a)cos(a)' },
        { name: 'Double Angle Formula (Cosine)', content: 'cos(2a) = cos<sup>2</sup>(a) - sin<sup>2</sup>(a)' },
        { name: 'Double Angle Formula (Tangent)', content: 'tan(2a) = 2tan(a) / (1 - tan<sup>2</sup>(a))' },
        { name: 'Half Angle Formula (Sine)', content: 'sin(a/2) = ±√((1 - cos(a)) / 2)' },
        { name: 'Half Angle Formula (Cosine)', content: 'cos(a/2) = ±√((1 + cos(a)) / 2)' },
        { name: 'Half Angle Formula (Tangent)', content: 'tan(a/2) = ±√((1 - cos(a)) / (1 + cos(a)))' },
        { name: 'Sum-to-Product Formula (Sine)', content: 'sin(a) + sin(b) = 2sin((a + b) / 2)cos((a - b) / 2)' },
        { name: 'Sum-to-Product Formula (Cosine)', content: 'cos(a) + cos(b) = 2cos((a + b) / 2)cos((a - b) / 2)' },
        { name: 'Difference-to-Product Formula (Sine)', content: 'sin(a) - sin(b) = 2cos((a + b) / 2)sin((a - b) / 2)' },
        { name: 'Difference-to-Product Formula (Cosine)', content: 'cos(a) - cos(b) = -2sin((a + b) / 2)sin((a - b) / 2)' },
        { name: 'Product-to-Sum Formula (Sine)', content: 'sin(a)sin(b) = 0.5[cos(a - b) - cos(a + b)]' },
        { name: 'Product-to-Sum Formula (Cosine)', content: 'cos(a)cos(b) = 0.5[cos(a - b) + cos(a + b)]' },
        { name: 'Product-to-Sum Formula (Sine and Cosine)', content: 'sin(a)cos(b) = 0.5[sin(a + b) + sin(a - b)]' },
        { name: 'Cofunction Identity (Sine)', content: 'sin(90° - θ) = cos(θ)' },
        { name: 'Cofunction Identity (Cosine)', content: 'cos(90° - θ) = sin(θ)' },
        { name: 'Cofunction Identity (Tangent)', content: 'tan(90° - θ) = cot(θ)' },
        { name: 'Cofunction Identity (Cotangent)', content: 'cot(90° - θ) = tan(θ)' },
        { name: 'Cofunction Identity (Secant)', content: 'sec(90° - θ) = csc(θ)' },
        { name: 'Cofunction Identity (Cosecant)', content: 'csc(90° - θ) = sec(θ)' },
        { name: 'Pythagorean Identity (Sine and Cosine)', content: 'sin<sup>2</sup>(θ) + cos<sup>2</sup>(θ) = 1' },
        { name: 'Pythagorean Identity (Tangent and Secant)', content: '1 + tan<sup>2</sup>(θ) = sec<sup>2</sup>(θ)' },
        { name: 'Pythagorean Identity (Cotangent and Cosecant)', content: '1 + cot<sup>2</sup>(θ) = csc<sup>2</sup>(θ)' },
        { name: 'Reciprocal Identity (Sine)', content: 'sin(θ) = 1 / csc(θ)' },
        { name: 'Reciprocal Identity (Cosine)', content: 'cos(θ) = 1 / sec(θ)' },
        { name: 'Reciprocal Identity (Tangent)', content: 'tan(θ) = 1 / cot(θ)' },
        { name: 'Reciprocal Identity (Cotangent)', content: 'cot(θ) = 1 / tan(θ)' },
        { name: 'Reciprocal Identity (Secant)', content: 'sec(θ) = 1 / cos(θ)' },
        { name: 'Reciprocal Identity (Cosecant)', content: 'csc(θ) = 1 / sin(θ)' },
        { name: 'Complementary Angle Identity (Sine)', content: 'sin(θ) = cos(90° - θ)' },
        { name: 'Complementary Angle Identity (Cosine)', content: 'cos(θ) = sin(90° - θ)' },
        { name: 'Complementary Angle Identity (Tangent)', content: 'tan(θ) = cot(90° - θ)' },
        { name: 'Complementary Angle Identity (Cotangent)', content: 'cot(θ) = tan(90° - θ)' },
        { name: 'Complementary Angle Identity (Secant)', content: 'sec(θ) = csc(90° - θ)' },
        { name: 'Complementary Angle Identity (Cosecant)', content: 'csc(θ) = sec(90° - θ)' },
        { name: 'Sum of Angles in Triangle', content: 'A + B + C = 180°' },
        { name: 'Law of Sines', content: 'a/sin(A) = b/sin(B) = c/sin(C)' },
        { name: 'Law of Cosines', content: 'c<sup>2</sup> = a<sup>2</sup> + b<sup>2</sup> - 2ab cos(C)' },
        { name: 'Law of Tangents', content: '(a - b) / (a + b) = tan[(A - B) / 2] / tan[(A + B) / 2]' },
        { name: 'Sine of Sum of Angles', content: 'sin(a + b) = sin(a)cos(b) + cos(a)sin(b)' },
        { name: 'Cosine of Sum of Angles', content: 'cos(a + b) = cos(a)cos(b) - sin(a)sin(b)' },
        { name: 'Tangent of Sum of Angles', content: 'tan(a + b) = (tan(a) + tan(b)) / (1 - tan(a)tan(b))' },
        { name: 'Sine of Difference of Angles', content: 'sin(a - b) = sin(a)cos(b) - cos(a)sin(b)' },
        { name: 'Cosine of Difference of Angles', content: 'cos(a - b) = cos(a)cos(b) + sin(a)sin(b)' },
        { name: 'Tangent of Difference of Angles', content: 'tan(a - b) = (tan(a) - tan(b)) / (1 + tan(a)tan(b))' },
        { name: 'Sine of Double Angle', content: 'sin(2a) = 2sin(a)cos(a)' },
        { name: 'Cosine of Double Angle', content: 'cos(2a) = cos<sup>2</sup>(a) - sin<sup>2</sup>(a)' },
        { name: 'Tangent of Double Angle', content: 'tan(2a) = 2tan(a) / (1 - tan<sup>2</sup>(a))' },
        { name: 'Sine of Half Angle', content: 'sin(a/2) = ±√((1 - cos(a)) / 2)' },
        { name: 'Cosine of Half Angle', content: 'cos(a/2) = ±√((1 + cos(a)) / 2)' },
        { name: 'Tangent of Half Angle', content: 'tan(a/2) = ±√((1 - cos(a)) / (1 + cos(a)))' },
        { name: 'Cotangent of Half Angle', content: 'cot(a/2) = ±√((1 + cos(a)) / (1 - cos(a)))' },
        { name: 'Sine of Triple Angle', content: 'sin(3a) = 3sin(a) - 4sin<sup>3</sup>(a)' },
        { name: 'Cosine of Triple Angle', content: 'cos(3a) = 4cos<sup>3</sup>(a) - 3cos(a)' },
        { name: 'Tangent of Triple Angle', content: 'tan(3a) = (3tan(a) - tan<sup>3</sup>(a)) / (1 - 3tan<sup>2</sup>(a))' },
        { name: 'Sine of Quadruple Angle', content: 'sin(4a) = 8sin(a)cos(a)cos(2a)' },
        { name: 'Cosine of Quadruple Angle', content: 'cos(4a) = 1 - 8sin<sup>2</sup>(a)cos<sup>2</sup>(a)' },
        { name: 'Tangent of Quadruple Angle', content: 'tan(4a) = (4tan(a) - 4tan<sup>3</sup>(a)) / (1 - 6tan<sup>2</sup>(a) + tan<sup>4</sup>(a))' },
        { name: 'Cotangent of Double Angle', content: 'cot(2a) = (cot<sup>2</sup>(a) - 1) / (2cot(a))' },
        { name: 'Cotangent of Triple Angle', content: 'cot(3a) = (cot<sup>3</sup>(a) - 3cot(a)) / (3cot<sup>2</sup>(a) - 1)' },
        { name: 'Secant of Double Angle', content: 'sec(2a) = sec<sup>2</sup>(a) / (2 - sec<sup>2</sup>(a))' },
        { name: 'Cosecant of Double Angle', content: 'csc(2a) = csc(a)sec(a) / 2' },
        { name: 'Sine-Cosine Relation', content: 'sin(a) = cos(90° - a)' },
        { name: 'Cosine-Sine Relation', content: 'cos(a) = sin(90° - a)' },
        { name: 'Sine of Sum of Three Angles', content: 'sin(a + b + c) = sin(a)cos(b)cos(c) + cos(a)sin(b)cos(c) + cos(a)cos(b)sin(c) - sin(a)sin(b)sin(c)' },
        { name: 'Cosine of Sum of Three Angles', content: 'cos(a + b + c) = cos(a)cos(b)cos(c) - sin(a)sin(b)cos(c) - sin(a)cos(b)sin(c) - cos(a)sin(b)sin(c)' },
        { name: 'Tangent of Sum of Three Angles', content: 'tan(a + b + c) = (tan(a) + tan(b) + tan(c) - tan(a)tan(b)tan(c)) / (1 - tan(a)tan(b) - tan(b)tan(c) - tan(c)tan(a))' },
        { name: 'Inverse Sine Function', content: 'sin<sup>-1</sup>(x) = θ' / '/sin(θ) = x' },
        { name: 'Inverse Cosine Function', content: 'cos<sup>-1</sup>(x) = θ' / '/cos(θ) = x' },
        { name: 'Inverse Tangent Function', content: 'tan<sup>-1</sup>(x) = θ' / 'tan(θ) = x' },
        { name: 'Inverse Cotangent Function', content: 'cot<sup>-1</sup>(x) = θ' / 'cot(θ) = x' },
        { name: 'Inverse Secant Function', content: 'sec<sup>-1</sup>(x) = θ' / 'sec(θ) = x' },
        { name: 'Inverse Cosecant Function', content: 'csc<sup>-1</sup>(x) = θ' / 'csc(θ) = x' },
        { name: 'Sine of Sum of Multiple Angles', content: 'sin(nθ) = nC<sub>k=0</sub>(-1)<sup>k</sup>sin<sup>(n-2k)(θ)</sup>cos<sup>2k</sup>(θ)' },
        { name: 'Cosine of Sum of Multiple Angles', content: 'cos(nθ) = nC<sub>k=0</sub>(-1)<sup>k</sup>cos<sup>(n-2k)(θ)</sup>sin<sup>2k</sup>(θ)' },
        { name: 'Tangent of Sum of Multiple Angles', content: 'tan(nθ) = nC<sub>k=0</sub>(-1)<sup>k</sup>tan<sup>(n-2k)(θ)</sup>sec<sup>2k</sup>(θ)' },
        { name: 'Sine of (a + b + c + ...)', content: 'sin(a + b + c + ...) = sin(a)cos(b)cos(c)... + cos(a)sin(b)cos(c)... + cos(a)cos(b)sin(c)... - sin(a)sin(b)sin(c)...' },
        { name: 'Cosine of (a + b + c + ...)', content: 'cos(a + b + c + ...) = cos(a)cos(b)cos(c)... - sin(a)sin(b)cos(c)... - sin(a)cos(b)sin(c)... - cos(a)sin(b)sin(c)...' },
        { name: 'Tangent of (a + b + c + ...)', content: 'tan(a + b + c + ...) = (tan(a) + tan(b) + tan(c)...) / (1 - tan(a)tan(b) - tan(b)tan(c) - tan(c)tan(a)...)' },
        { name: 'Cosecant of Sum of Angles', content: 'csc(a + b) = 1 / sin(a + b)' },
        { name: 'Secant of Sum of Angles', content: 'sec(a + b) = 1 / cos(a + b)' },
        { name: 'Cotangent of Sum of Angles', content: 'cot(a + b) = 1 / tan(a + b)' },
        { name: 'Secant of Sum of Multiple Angles', content: 'sec(a + b + c + ...) = 1 / cos(a + b + c + ...)' },
        { name: 'Cosecant of Sum of Multiple Angles', content: 'csc(a + b + c + ...) = 1 / sin(a + b + c + ...)' },
        { name: 'Cotangent of Sum of Multiple Angles', content: 'cot(a + b + c + ...) = 1 / tan(a + b + c + ...)' },
        { name: 'Sine of (a + b - c)', content: 'sin(a + b - c) = sin(a)cos(b)cos(c) - cos(a)sin(b)cos(c) - cos(a)cos(b)sin(c) - sin(a)sin(b)sin(c)' },
        { name: 'Cosine of (a + b - c)', content: 'cos(a + b - c) = cos(a)cos(b)cos(c) + sin(a)sin(b)cos(c) + sin(a)cos(b)sin(c) + cos(a)sin(b)sin(c)' },
        { name: 'Tangent of (a + b - c)', content: 'tan(a + b - c) = (tan(a) + tan(b) - tan(c) - tan(a)tan(b)tan(c)) / (1 - tan(a)tan(b) + tan(b)tan(c) + tan(c)tan(a))' },
        { name: 'Inverse Sine of Sum', content: 'sin<sup>-1</sup>(x) + sin<sup>-1</sup>(y) = sin<sup>-1</sup>(x√(1-y<sup>2</sup>) + y√(1-x<sup>2</sup>))' },
        { name: 'Inverse Cosine of Sum', content: 'cos<sup>-1</sup>(x) + cos<sup>-1</sup>(y) = cos<sup>-1</sup>(xy - √(1-x<sup>2</sup>)√(1-y<sup>2</sup>))' },
        { name: 'Inverse Tangent of Sum', content: 'tan<sup>-1</sup>(x) + tan<sup>-1</sup>(y) = tan<sup>-1</sup>((x + y) / (1 - xy))' },
        { name: 'Inverse Cotangent of Sum', content: 'cot<sup>-1</sup>(x) + cot<sup>-1</sup>(y) = cot<sup>-1</sup>((xy - 1) / (x + y))' },
        { name: 'Inverse Sine of Difference', content: 'sin<sup>-1</sup>(x) - sin<sup>-1</sup>(y) = sin<sup>-1</sup>(x√(1-y<sup>2</sup>) - y√(1-x<sup>2</sup>))' },
        { name: 'Inverse Cosine of Difference', content: 'cos<sup>-1</sup>(x) - cos<sup>-1</sup>(y) = cos<sup>-1</sup>(xy + √(1-x<sup>2</sup>)√(1-y<sup>2</sup>))' },
        { name: 'Inverse Tangent of Difference', content: 'tan<sup>-1</sup>(x) - tan<sup>-1</sup>(y) = tan<sup>-1</sup>((x - y) / (1 + xy))' },
        { name: 'Inverse Cotangent of Difference', content: 'cot<sup>-1</sup>(x) - cot<sup>-1</sup>(y) = cot<sup>-1</sup>((xy + 1) / (x - y))' },
        { name: 'Sine of Multiple Angles', content: 'sin(nθ) = n sin(θ) - (n(n-1)sin(θ) cos(θ))/2 + ...' },
        { name: 'Cosine of Multiple Angles', content: 'cos(nθ) = n cos(θ) - (n(n-1)cos(θ) sin(θ))/2 + ...' },
        { name: 'Tangent of Multiple Angles', content: 'tan(nθ) = (n tan(θ) - (n(n-1)tan<sup>2</sup>(θ))/2 + ...' },
        { name: 'Cotangent of Multiple Angles', content: 'cot(nθ) = (n cot(θ) - (n(n-1)cot<sup>2</sup>(θ))/2 + ...' },
        { name: 'Secant of Multiple Angles', content: 'sec(nθ) = sec(θ) * [1 - tan<sup>2</sup>(θ) + ...]' },
        { name: 'Cosecant of Multiple Angles', content: 'csc(nθ) = csc(θ) * [1 - cot<sup>2</sup>(θ) + ...]' },
        { name: 'Sum of Sine and Cosine', content: 'sin(x) + cos(x) = √2 sin(x + 45°)' },
        { name: 'Difference of Sine and Cosine', content: 'sin(x) - cos(x) = √2 sin(x - 45°)' },
        { name: 'Sum of Sine and Sine', content: 'sin(x) + sin(y) = 2 sin((x + y) / 2) cos((x - y) / 2)' },
        { name: 'Difference of Sine and Sine', content: 'sin(x) - sin(y) = 2 cos((x + y) / 2) sin((x - y) / 2)' },
        { name: 'Sum of Cosine and Cosine', content: 'cos(x) + cos(y) = 2 cos((x + y) / 2) cos((x - y) / 2)' },
        { name: 'Difference of Cosine and Cosine', content: 'cos(x) - cos(y) = -2 sin((x + y) / 2) sin((x - y) / 2)' },
        { name: 'Sum of Tangent and Tangent', content: 'tan(x) + tan(y) = (sin(x+y)) / (cos(x) cos(y))' },
        { name: 'Difference of Tangent and Tangent', content: 'tan(x) - tan(y) = (sin(x-y)) / (cos(x) cos(y))' },
        { name: 'Sum of Cotangent and Cotangent', content: 'cot(x) + cot(y) = (sin(x+y)) / (sin(x) sin(y))' },
        { name: 'Difference of Cotangent and Cotangent', content: 'cot(x) - cot(y) = (sin(x-y)) / (sin(x) sin(y))' },
        { name: 'Sum of Secant and Secant', content: 'sec(x) + sec(y) = 2 sec((x + y) / 2) sec((x - y) / 2)' },
        { name: 'Difference of Secant and Secant', content: 'sec(x) - sec(y) = -2 sec((x + y) / 2) sec((x - y) / 2)' },
        { name: 'Sum of Cosecant and Cosecant', content: 'csc(x) + csc(y) = 2 csc((x + y) / 2) csc((x - y) / 2)' },
        { name: 'Difference of Cosecant and Cosecant', content: 'csc(x) - csc(y) = -2 csc((x + y) / 2) csc((x - y) / 2)' },
        { name: 'Sum of Sin<sup>2</sup> and Cos<sup>2</sup>', content: 'sin<sup>2</sup>(x) + cos<sup>2</sup>(x) = 1' },
        { name: 'Sum of Tan<sup>2</sup> and Sec<sup>2</sup>', content: 'tan<sup>2</sup>(x) + sec<sup>2</sup>(x) = sec<sup>2</sup>(x)' },
        { name: 'Sum of Cot<sup>2</sup> and Csc<sup>2</sup>', content: 'cot<sup>2</sup>(x) + csc<sup>2</sup>(x) = csc<sup>2</sup>(x)' },
        { name: 'Sin<sup>2</sup> in Terms of Cos', content: 'sin<sup>2</sup>(x) = 1 - cos<sup>2</sup>(x)' },
        { name: 'Cos<sup>2</sup> in Terms of Sin', content: 'cos<sup>2</sup>(x) = 1 - sin<sup>2</sup>(x)' },
        { name: 'Tan<sup>2</sup> in Terms of Sec', content: 'tan<sup>2</sup>(x) = sec<sup>2</sup>(x) - 1' },
        { name: 'Cot<sup>2</sup> in Terms of Csc', content: 'cot<sup>2</sup>(x) = csc<sup>2</sup>(x) - 1' },
        { name: 'Sec<sup>2</sup> in Terms of Tan', content: 'sec<sup>2</sup>(x) = 1 + tan<sup>2</sup>(x)' },
        { name: 'Csc<sup>2</sup> in Terms of Cot', content: 'csc<sup>2</sup>(x) = 1 + cot<sup>2</sup>(x)' },
        { name: 'Double Angle Formula (Secant)', content: 'sec(2x) = sec<sup>2</sup>(x) / (1 - tan<sup>2</sup>(x))' },
        { name: 'Double Angle Formula (Cosecant)', content: 'csc(2x) = csc(x) sec(x) / 2' },
        { name: 'Half Angle Formula (Secant)', content: 'sec(x/2) = ±√(2 / (1 + cos(x)))' },
        { name: 'Half Angle Formula (Cosecant)', content: 'csc(x/2) = ±√(2 / (1 - cos(x)))' },
        { name: 'Sum of Sin<sup>2</sup> and Sin<sup>2</sup>', content: 'sin<sup>2</sup>(x) + sin<sup>2</sup>(y) = (1 - cos(x-y))/2 + (1 - cos(x+y))/2' },
        { name: 'Sum of Cos<sup>2</sup> and Cos<sup>2</sup>', content: 'cos<sup>2</sup>(x) + cos<sup>2</sup>(y) = (1 + cos(x-y))/2 + (1 + cos(x+y))/2' },
        { name: 'Laplace Transform of 1', content: 'L{1} = 1/s' },
        { name: 'Laplace Transform of t', content: 'L{t} = 1/s<sup>2</sup>' },
        { name: 'Laplace Transform of t<sup>n</sup>', content: 'L{t<sup>n</sup>} = n!/s<sup>n+1</sup>' },
        { name: 'Laplace Transform of e<sup>at</sup>', content: 'L{e<sup>at</sup>} = 1/(s - a)' },
        { name: 'Laplace Transform of cos(bt)', content: 'L{cos(bt)} = s/(s<sup>2</sup> + b<sup>2</sup>)' },
        { name: 'Laplace Transform of sin(bt)', content: 'L{sin(bt)} = b/(s<sup>2</sup> + b<sup>2</sup>)' },
        { name: 'Laplace Transform of e<sup>at</sup>sin(bt)', content: 'L{e<sup>at</sup>sin(bt)} = b/((s - a)<sup>2</sup> + b<sup>2</sup>)' },
        { name: 'Laplace Transform of e<sup>at</sup>cos(bt)', content: 'L{e<sup>at</sup>cos(bt)} = (s - a)/((s - a)<sup>2</sup> + b<sup>2</sup>)' },
        { name: 'Laplace Transform of t e<sup>at</sup>', content: 'L{t e<sup>at</sup>} = 1/(s - a)<sup>2</sup>' },
        { name: 'Fourier Transform of 1', content: 'F{1} = δ(ω)' },
        { name: 'Fourier Transform of e<sup>-at</sup>u(t)', content: 'F{e<sup>-at</sup>u(t)} = 1/(a + jω)' },
        { name: 'Fourier Transform of cos(ω<sub>0</sub>t)', content: 'F{cos(ω<sub>0</sub>t)} = π[δ(ω - ω<sub>0</sub>) + δ(ω + ω<sub>0</sub>)]' },
        { name: 'Fourier Transform of sin(ω<sub>0</sub>t)', content: 'F{sin(ω<sub>0</sub>t)} = jπ[δ(ω - ω<sub>0</sub>) - δ(ω + ω<sub>0</sub>)]' },
        { name: 'Fourier Transform of e<sup>-a|t|</sup>', content: 'F{e<sup>-a|t|</sup>} = 2a/(a<sup>2</sup> + ω<sup>2</sup>)' },
        { name: 'Gradient of a Scalar Field', content: '∇φ = (∂φ/∂x, ∂φ/∂y, ∂φ/∂z)' },
        { name: 'Divergence of a Vector Field', content: '∇·F = ∂F<sub>x</sub>/∂x + ∂F<sub>y</sub>/∂y + ∂F<sub>z</sub>/∂z' },
        { name: 'Curl of a Vector Field', content: '∇×F = (∂F<sub>z</sub>/∂y - ∂F<sub>y</sub>/∂z, ∂F<sub>x</sub>/∂z - ∂F<sub>z</sub>/∂x, ∂F<sub>y</sub>/∂x - ∂F<sub>x</sub>/∂y)' },
        { name: 'Laplacian of a Scalar Field', content: '∇<sup>2</sup>φ = ∂<sup>2</sup>φ/∂x<sup>2</sup> + ∂<sup>2</sup>φ/∂y<sup>2</sup> + ∂<sup>2</sup>φ/∂z<sup>2</sup>' },
        { name: 'Directional Derivative', content: 'D<sub>u</sub>φ = ∇φ · u' },
        { name: 'Line Integral', content: '∫<sub>C</sub> F · dr = ∫<sub>a</sub><sup>b</sup> F(r(t)) · r\'(t) dt' },
        { name: 'Surface Integral', content: '∬<sub>S</sub> F · dS' },
        { name: 'Volume Integral', content: '∭<sub>V</sub> F dV' },
        { name: 'Green\'s Theorem', content: '∮<sub>C</sub> L dx + M dy = ∬<sub>D</sub> (∂M/∂x - ∂L/∂y) dA' },
        { name: 'Stokes\' Theorem', content: '∮<sub>C</sub> F · dr = ∬<sub>S</sub> (∇ × F) · dS' },
        { name: 'Divergence Theorem', content: '∬<sub>S</sub> F · dS = ∭<sub>V</sub> (∇ · F) dV' },
        { name: 'Scalar Triple Product', content: 'A · (B × C)' },
        { name: 'Vector Triple Product', content: 'A × (B × C) = (A · C)B - (A · B)C' },
        { name: 'Gradient of f(g(x,y,z))', content: '∇f(g(x,y,z)) = f\'(g) ∇g(x,y,z)' },
        { name: 'Gradient of a Product', content: '∇(fg) = f∇g + g∇f' },
        { name: 'Gradient of a Quotient', content: '∇(f/g) = (g∇f - f∇g)/g<sup>2</sup>' },
        { name: 'Gradient of a Power', content: '∇(f<sup>n</sup>) = n f<sup>n-1</sup> ∇f' },
        { name: 'Gradient in Polar Coordinates', content: '∇f = (∂f/∂r, 1/r ∂f/∂θ)' },
        { name: 'Gradient in Cylindrical Coordinates', content: '∇f = (∂f/∂r, 1/r ∂f/∂θ, ∂f/∂z)' },
        { name: 'Gradient in Spherical Coordinates', content: '∇f = (∂f/∂ρ, 1/ρ ∂f/∂θ, 1/ρsinθ ∂f/∂φ)' },
        { name: 'Curl in Cylindrical Coordinates', content: '∇×F = (1/r ∂F<sub>z</sub>/∂θ - ∂F<sub>θ</sub>/∂z, ∂F<sub>r</sub>/∂z - ∂F<sub>z</sub>/∂r, 1/r (∂(rF<sub>θ</sub>)/∂r - ∂F<sub>r</sub>/∂θ))' },
        { name: 'Integral of a Constant', content: '∫a dx = ax + C' },
        { name: 'Integral of x^n', content: '∫x<sup>n</sup> dx = (1/(n+1))x<sup>n+1</sup> + C' },
        { name: 'Integral of e^x', content: '∫e<sup>x</sup> dx = e<sup>x</sup> + C' },
        { name: 'Integral of a^x', content: '∫a<sup>x</sup> dx = (a<sup>x</sup>/ln(a)) + C' },
        { name: 'Integral of 1/x', content: '∫(1/x) dx = ln|x| + C' },
        { name: 'Integral of sin(x)', content: '∫sin(x) dx = -cos(x) + C' },
        { name: 'Integral of cos(x)', content: '∫cos(x) dx = sin(x) + C' },
        { name: 'Integral of tan(x)', content: '∫tan(x) dx = -ln|cos(x)| + C' },
        { name: 'Integral of cot(x)', content: '∫cot(x) dx = ln|sin(x)| + C' },
        { name: 'Integral of sec(x)', content: '∫sec(x) dx = ln|sec(x) + tan(x)| + C' },
        { name: 'Integral of csc(x)', content: '∫csc(x) dx = -ln|csc(x) + cot(x)| + C' },
        { name: 'Integral of sec^2(x)', content: '∫sec<sup>2</sup>(x) dx = tan(x) + C' },
        { name: 'Integral of csc^2(x)', content: '∫csc<sup>2</sup>(x) dx = -cot(x) + C' },
        { name: 'Integral of sec(x)tan(x)', content: '∫sec(x)tan(x) dx = sec(x) + C' },
        { name: 'Integral of csc(x)cot(x)', content: '∫csc(x)cot(x) dx = -csc(x) + C' },
        { name: 'Integral of sinh(x)', content: '∫sinh(x) dx = cosh(x) + C' },
        { name: 'Integral of cosh(x)', content: '∫cosh(x) dx = sinh(x) + C' },
        { name: 'Integral of tanh(x)', content: '∫tanh(x) dx = ln|cosh(x)| + C' },
        { name: 'Integral of coth(x)', content: '∫coth(x) dx = ln|sinh(x)| + C' },
        { name: 'Integral of sech(x)', content: '∫sech(x) dx = 2arctan(tanh(x/2)) + C' },
        { name: 'Integral of csch(x)', content: '∫csch(x) dx = ln|tanh(x/2)| + C' },
        { name: 'Integral of arctan(x)', content: '∫arctan(x) dx = x arctan(x) - (1/2)ln(1 + x<sup>2</sup>) + C' },
        { name: 'Integral of arcsin(x)', content: '∫arcsin(x) dx = x arcsin(x) + √(1 - x<sup>2</sup>) + C' },
        { name: 'Integral of arccos(x)', content: '∫arccos(x) dx = x arccos(x) - √(1 - x<sup>2</sup>) + C' },
        { name: 'Integral of arccot(x)', content: '∫arccot(x) dx = x arccot(x) + (1/2)ln(1 + x<sup>2</sup>) + C' },
        { name: 'Integral of arcsec(x)', content: '∫arcsec(x) dx = x arcsec(x) - ln|x + √(x<sup>2</sup> - 1)| + C' },
        { name: 'Integral of arccsc(x)', content: '∫arccsc(x) dx = x arccsc(x) + ln|x + √(x<sup>2</sup> - 1)| + C' },
        { name: 'Integral of sinh^2(x)', content: '∫sinh<sup>2</sup>(x) dx = (1/2)sinh(x)cosh(x) - (1/2)x + C' },
        { name: 'Integral of cosh^2(x)', content: '∫cosh<sup>2</sup>(x) dx = (1/2)sinh(x)cosh(x) + (1/2)x + C' },
        { name: 'Integral of tanh^2(x)', content: '∫tanh<sup>2</sup>(x) dx = x - tanh(x) + C' },
        { name: 'Integral of coth^2(x)', content: '∫coth<sup>2</sup>(x) dx = -x + coth(x) + C' },
        { name: 'Integral of sech^2(x)', content: '∫sech<sup>2</sup>(x) dx = tanh(x) + C' },
        { name: 'Integral of csch^2(x)', content: '∫csch<sup>2</sup>(x) dx = -coth(x) + C' },
        { name: 'Integral of sinh(x)cosh(x)', content: '∫sinh(x)cosh(x) dx = (1/2)cosh<sup>2</sup>(x) + C' },
        { name: 'Integral of 1/(x^2 + a^2)', content: '∫(1/(x<sup>2</sup> + a<sup>2</sup>)) dx = (1/a)arctan(x/a) + C' },
        { name: 'Integral of 1/(x^2 - a^2)', content: '∫(1/(x<sup>2</sup> - a<sup>2</sup>)) dx = (1/2a)ln|(x - a)/(x + a)| + C' },
        { name: 'Integral of 1/√(a^2 - x^2)', content: '∫(1/√(a<sup>2</sup> - x<sup>2</sup>)) dx = arcsin(x/a) + C' },
        { name: 'Integral of 1/√(x^2 + a^2)', content: '∫(1/√(x<sup>2</sup> + a<sup>2</sup>)) dx = ln|x + √(x<sup>2</sup> + a<sup>2</sup>)| + C' },
        { name: 'Integral of 1/√(x^2 - a^2)', content: '∫(1/√(x<sup>2</sup> - a<sup>2</sup>)) dx = ln|x + √(x<sup>2</sup> - a<sup>2</sup>)| + C' },
        { name: 'Integral of e^(ax)', content: '∫e<sup>ax</sup> dx = (1/a)e<sup>ax</sup> + C' },
        { name: 'Integral of sin(ax)', content: '∫sin(ax) dx = -(1/a)cos(ax) + C' },
        { name: 'Integral of cos(ax)', content: '∫cos(ax) dx = (1/a)sin(ax) + C' },
        { name: 'Integral of sec^2(ax)', content: '∫sec<sup>2</sup>(ax) dx = (1/a)tan(ax) + C' },
        { name: 'Integral of csc^2(ax)', content: '∫csc<sup>2</sup>(ax) dx = -(1/a)cot(ax) + C' },
        { name: 'Integral of sec(ax)tan(ax)', content: '∫sec(ax)tan(ax) dx = (1/a)sec(ax) + C' },
        { name: 'Derivative of a Constant', content: 'd/dx (c) = 0' },
        { name: 'Power Rule', content: 'd/dx (x<sup>n</sup>) = nx<sup>n-1</sup>' },
        { name: 'Derivative of e^x', content: 'd/dx (e<sup>x</sup>) = e<sup>x</sup>' },
        { name: 'Derivative of a^x', content: 'd/dx (a<sup>x</sup>) = a<sup>x</sup>ln(a)' },
        { name: 'Derivative of ln(x)', content: 'd/dx (ln(x)) = 1/x' },
        { name: 'Derivative of sin(x)', content: 'd/dx (sin(x)) = cos(x)' },
        { name: 'Derivative of cos(x)', content: 'd/dx (cos(x)) = -sin(x)' },
        { name: 'Derivative of tan(x)', content: 'd/dx (tan(x)) = sec<sup>2</sup>(x)' },
        { name: 'Derivative of cot(x)', content: 'd/dx (cot(x)) = -csc<sup>2</sup>(x)' },
        { name: 'Derivative of sec(x)', content: 'd/dx (sec(x)) = sec(x)tan(x)' },
        { name: 'Derivative of csc(x)', content: 'd/dx (csc(x)) = -csc(x)cot(x)' },
        { name: 'Product Rule', content: 'd/dx (uv) = u\'v + uv\'' },
        { name: 'Quotient Rule', content: 'd/dx (u/v) = (u\'v - uv\')/v<sup>2</sup>' },
        { name: 'Chain Rule', content: 'd/dx (f(g(x))) = f\'(g(x))g\'(x)' },
        { name: 'Derivative of sinh(x)', content: 'd/dx (sinh(x)) = cosh(x)' },
        { name: 'Derivative of cosh(x)', content: 'd/dx (cosh(x)) = sinh(x)' },
        { name: 'Derivative of tanh(x)', content: 'd/dx (tanh(x)) = sech<sup>2</sup>(x)' },
        { name: 'Derivative of coth(x)', content: 'd/dx (coth(x)) = -csch<sup>2</sup>(x)' },
        { name: 'Derivative of sech(x)', content: 'd/dx (sech(x)) = -sech(x)tanh(x)' },
        { name: 'Derivative of csch(x)', content: 'd/dx (csch(x)) = -csch(x)coth(x)' },
        { name: 'Derivative of arcsin(x)', content: 'd/dx (arcsin(x)) = 1/√(1 - x<sup>2</sup>)' },
        { name: 'Derivative of arccos(x)', content: 'd/dx (arccos(x)) = -1/√(1 - x<sup>2</sup>)' },
        { name: 'Derivative of arctan(x)', content: 'd/dx (arctan(x)) = 1/(1 + x<sup>2</sup>)' },
        { name: 'Derivative of arccot(x)', content: 'd/dx (arccot(x)) = -1/(1 + x<sup>2</sup>)' },
        { name: 'Derivative of arcsec(x)', content: 'd/dx (arcsec(x)) = 1/(|x|√(x<sup>2</sup> - 1))' },
        { name: 'Derivative of arccsc(x)', content: 'd/dx (arccsc(x)) = -1/(|x|√(x<sup>2</sup> - 1))' },
        { name: 'Derivative of sinh<sup>-1</sup>(x)', content: 'd/dx (sinh<sup>-1</sup>(x)) = 1/√(x<sup>2</sup> + 1)' },
        { name: 'Derivative of cosh<sup>-1</sup>(x)', content: 'd/dx (cosh<sup>-1</sup>(x)) = 1/√(x<sup>2</sup> - 1)' },
        { name: 'Derivative of tanh<sup>-1</sup>(x)', content: 'd/dx (tanh<sup>-1</sup>(x)) = 1/(1 - x<sup>2</sup>)' },
        { name: 'Derivative of coth<sup>-1</sup>(x)', content: 'd/dx (coth<sup>-1</sup>(x)) = -1/(1 - x<sup>2</sup>)' },
        { name: 'Derivative of sech<sup>-1</sup>(x)', content: 'd/dx (sech<sup>-1</sup>(x)) = -1/(x√(1 - x<sup>2</sup>))' },
        { name: 'Derivative of csch<sup>-1</sup>(x)', content: 'd/dx (csch<sup>-1</sup>(x)) = -1/(|x|√(1 + x<sup>2</sup>))' },
        { name: 'Implicit Differentiation', content: 'd/dx [F(x,y)] = ∂F/∂x + (∂F/∂y)(dy/dx)' },
        { name: 'Higher Order Derivative', content: 'd<sup>n</sup>/dx<sup>n</sup> [f(x)]' },
        { name: 'Derivative of a Sum', content: 'd/dx [u + v] = u\' + v\'' },
        { name: 'Derivative of a Difference', content: 'd/dx [u - v] = u\' - v\'' },
        { name: 'Derivative of a Product', content: 'd/dx [uv] = u\'v + uv\'' },
        { name: 'Derivative of a Quotient', content: 'd/dx [u/v] = (u\'v - uv\')/v<sup>2</sup>' },
        { name: 'Derivative of an Inverse Function', content: '(f<sup>-1</sup>)\'(y) = 1 / f\'(x)' },
        { name: 'Logarithmic Differentiation', content: 'd/dx [ln|u|] = u\' / u' },
        { name: 'Exponential Differentiation', content: 'd/dx [a<sup>u</sup>] = a<sup>u</sup>ln(a)u\'' },
        { name: 'Derivative of an Exponential Function', content: 'd/dx [e<sup>u</sup>] = e<sup>u</sup>u\'' },
        { name: 'Derivative of a Logarithmic Function', content: 'd/dx [ln|u|] = u\' / u' },
        { name: 'Mean Value Theorem', content: 'f\'(c) = (f(b) - f(a)) / (b - a)' },
        { name: 'Rolle\'s Theorem', content: 'If f(a) = f(b), then there exists c in (a, b) such that f\'(c) = 0' },
        { name: 'L\'Hopital\'s Rule', content: 'If limit x→c [f(x)/g(x)] = 0/0 or ±∞/±∞, then limit x→c [f(x)/g(x)] = limit x→c [f\'(x)/g\'(x)]' },
        { name: 'Taylor Series', content: 'f(x) = ∑(f<sup>(n)</sup>(a) / n!) (x - a)<sup>n</sup>' },
        { name: 'Maclaurin Series', content: 'f(x) = ∑(f<sup>(n)</sup>(0) / n!) x<sup>n</sup>' },
        { name: 'Directional Derivative', content: 'D<sub>u</sub>f = ∇f · u' },
        { name: 'Gradient', content: '∇f = (∂f/∂x, ∂f/∂y, ∂f/∂z)' },
        { name: 'Mean', content: 'μ = (1/N) ∑x' },
        { name: 'Variance', content: 'σ<sup>2</sup> = (1/N) ∑(x - μ)<sup>2</sup>' },
        { name: 'Standard Deviation', content: 'σ = √[(1/N) ∑(x - μ)<sup>2</sup>]' },
        { name: 'Sample Variance', content: 's<sup>2</sup> = (1/(n-1)) ∑(x - x̄)<sup>2</sup>' },
        { name: 'Sample Standard Deviation', content: 's = √[(1/(n-1)) ∑(x - x̄)<sup>2</sup>]' },
        { name: 'Z-Score', content: 'z = (x - μ) / σ' },
        { name: 't-Score', content: 't = (x - x̄) / (s/√n)' },
        { name: 'Coefficient of Variation', content: 'CV = (σ / μ) * 100%' },
        { name: 'Skewness', content: 'γ = (1/N) ∑[(x - μ)/σ]<sup>3</sup>' },
        { name: 'Kurtosis', content: 'κ = (1/N) ∑[(x - μ)/σ]<sup>4</sup> - 3' },
        { name: 'Pearson Correlation Coefficient', content: 'r = ∑[(x - x̄)(y - ȳ)] / (n-1)s<sub>x</sub>s<sub>y</sub>' },
        { name: 'Spearman Rank Correlation', content: 'ρ = 1 - (6∑d<sup>2</sup>) / (n(n<sup>2</sup> - 1))' },
        { name: 'Simple Linear Regression', content: 'y = β<sub>0</sub> + β<sub>1</sub>x' },
        { name: 'Multiple Linear Regression', content: 'y = β<sub>0</sub> + β<sub>1</sub>x<sub>1</sub> + β<sub>2</sub>x<sub>2</sub> + ... + β<sub>k</sub>x<sub>k</sub>' },
        { name: 'Least Squares Estimate of Slope', content: 'β<sub>1</sub> = ∑[(x - x̄)(y - ȳ)] / ∑(x - x̄)<sup>2</sup>' },
        { name: 'Least Squares Estimate of Intercept', content: 'β<sub>0</sub> = ȳ - β<sub>1</sub>x̄' },
        { name: 'ANOVA F-Statistic', content: 'F = MS<sub>between</sub> / MS<sub>within</sub>' },
        { name: 'Chi-Square Statistic', content: 'χ<sup>2</sup> = ∑((O - E)<sup>2</sup> / E)' },
        { name: 't-Test Statistic', content: 't = (x̄ - μ) / (s/√n)' },
        { name: 'Pooled Standard Deviation', content: 's<sub>p</sub> = √[((n<sub>1</sub>-1)s<sub>1</sub><sup>2</sup> + (n<sub>2</sub>-1)s<sub>2</sub><sup>2</sup>) / (n<sub>1</sub> + n<sub>2</sub> - 2)]' },

        { name: 'Central Limit Theorem', content: 'For a large sample size, the sampling distribution of the sample mean approaches a normal distribution.' },
        { name: 'Law of Large Numbers', content: 'As n approaches infinity, the sample mean approaches the population mean.' },
        { name: 'Confidence Interval for Mean', content: 'CI = x̄ ± z*(σ/√n)' },
        { name: 'Confidence Interval for Proportion', content: 'CI = p̂ ± z*√[p̂(1-p̂)/n]' },
        { name: 'Margin of Error', content: 'ME = z*(σ/√n)' },
        { name: 'Relative Risk', content: 'RR = [a/(a+b)] / [c/(c+d)]' },
        { name: 'Odds Ratio', content: 'OR = (a/b) / (c/d)' },
        { name: 'Standard Error', content: 'SE = σ/√n' },
        { name: 'Coefficient of Determination (R²)', content: 'R² = 1 - (SS<sub>residual</sub> / SS<sub>total</sub>)' },
        { name: 'Adjusted R²', content: 'R²<sub>adj</sub> = 1 - [(1 - R²)(n - 1) / (n - k - 1)]' },
        { name: 'Sum of Squares Total (SST)', content: 'SST = ∑(y - ȳ)<sup>2</sup>' },
        { name: 'Sum of Squares Regression (SSR)', content: 'SSR = ∑(ŷ - ȳ)<sup>2</sup>' },
        { name: 'Sum of Squares Error (SSE)', content: 'SSE = ∑(y - ŷ)<sup>2</sup>' },
        { name: 'Logistic Regression Model', content: 'logit(p) = ln[p/(1-p)] = β<sub>0</sub> + β<sub>1</sub>x<sub>1</sub> + ... + β<sub>k</sub>x<sub>k</sub>' },
        { name: 'Log-Likelihood', content: 'LL = ∑(y<sub>i</sub>ln(p<sub>i</sub>) + (1 - y<sub>i</sub>)ln(1 - p<sub>i</sub>))' },
        { name: 'Probability of an Event', content: 'P(A) = Number of favorable outcomes / Total number of outcomes' },
        { name: 'Complement Rule', content: 'P(A\') = 1 - P(A)' },
        { name: 'Addition Rule', content: 'P(A ∪ B) = P(A) + P(B) - P(A ∩ B)' },
        { name: 'Multiplication Rule', content: 'P(A ∩ B) = P(A)P(B|A)' },
        { name: 'Conditional Probability', content: 'P(A|B) = P(A ∩ B) / P(B)' },
        { name: 'Bayes\' Theorem', content: 'P(A|B) = [P(B|A)P(A)] / P(B)' },
        { name: 'Law of Total Probability', content: 'P(B) = ∑ P(B|A_i)P(A_i)' },
        { name: 'Independent Events', content: 'P(A ∩ B) = P(A)P(B)' },
        { name: 'Mutually Exclusive Events', content: 'P(A ∩ B) = 0' },
        { name: 'Discrete Uniform Distribution', content: 'P(X = x) = 1/n' },
        { name: 'Binomial Distribution', content: 'P(X = k) = C(n, k)p^k(1-p)^(n-k)' },
        { name: 'Geometric Distribution', content: 'P(X = k) = (1-p)^(k-1)p' },
        { name: 'Negative Binomial Distribution', content: 'P(X = k) = C(k-1, r-1)p^r(1-p)^(k-r)' },
        { name: 'Hypergeometric Distribution', content: 'P(X = k) = [C(K, k) * C(N-K, n-k)] / C(N, n)' },
        { name: 'Poisson Distribution', content: 'P(X = k) = (λ^k * e^(-λ)) / k!' },
        { name: 'Exponential Distribution', content: 'P(X ≤ x) = 1 - e^(-λx)' },
        { name: 'Normal Distribution', content: 'f(x) = (1/√(2πσ^2))e^(-(x-μ)^2 / 2σ^2)' },
        { name: 'Standard Normal Distribution', content: 'P(Z ≤ z) = ∫_(-∞)^z (1/√(2π))e^(-t^2/2) dt' },
        { name: 'Cumulative Distribution Function', content: 'F(x) = P(X ≤ x)' },
        { name: 'Probability Density Function', content: 'f(x) = dF(x)/dx' },
        { name: 'Moment Generating Function', content: 'M_X(t) = E[e^(tX)]' },
        { name: 'Expected Value', content: 'E(X) = ∑xP(X = x)' },
        { name: 'Variance', content: 'Var(X) = E[(X - μ)^2]' },
        { name: 'Standard Deviation', content: 'σ = √Var(X)' },
        { name: 'Covariance', content: 'Cov(X, Y) = E[(X - μ_X)(Y - μ_Y)]' },
        { name: 'Correlation Coefficient', content: 'ρ = Cov(X, Y) / (σ_Xσ_Y)' },
        { name: 'Chebyshev\'s Inequality', content: 'P(|X - μ| ≥ kσ) ≤ 1/k^2' },
        { name: 'Markov\'s Inequality', content: 'P(X ≥ a) ≤ E(X)/a' },
        { name: 'Jensen\'s Inequality', content: 'φ(E(X)) ≤ E(φ(X))' },
        { name: 'Law of Large Numbers', content: 'As n → ∞, (1/n)∑X_i → μ' },
        { name: 'Central Limit Theorem', content: 'As n → ∞, (X̄ - μ) / (σ/√n) → N(0, 1)' },
        { name: 'Sample Mean', content: 'X̄ = (1/n) ∑X_i' },
        { name: 'Sample Variance', content: 's^2 = (1/(n-1)) ∑(X_i - X̄)^2' },
        { name: 'Bernoulli Distribution', content: 'P(X = k) = p^k(1-p)^(1-k)' },
        { name: 'Uniform Distribution (Continuous)', content: 'f(x) = 1/(b-a) for a ≤ x ≤ b' },
        { name: 'Chi-Square Distribution', content: 'f(x) = (1/(2^(k/2)Γ(k/2)))x^(k/2-1)e^(-x/2)' },
        { name: 'Student\'s t-Distribution', content: 'f(t) = (Γ((ν+1)/2))/(√(πν)Γ(ν/2))(1+t^2/ν)^(-(ν+1)/2)' },
        { name: 'F-Distribution', content: 'f(x) = (Γ((d_1+d_2)/2))/(Γ(d_1/2)Γ(d_2/2))(d_1/d_2)^(d_1/2)x^(d_1/2-1)(1+(d_1/d_2)x)^(-(d_1+d_2)/2)' },
        { name: 'Weibull Distribution', content: 'f(x) = (k/λ)(x/λ)^(k-1)e^(-(x/λ)^k)' },
        { name: 'Gamma Distribution', content: 'f(x) = (β^α)/(Γ(α))x^(α-1)e^(-βx)' },
        { name: 'Beta Distribution', content: 'f(x) = (Γ(α+β)/(Γ(α)Γ(β)))x^(α-1)(1-x)^(β-1)' },
        { name: 'Multinomial Distribution', content: 'P(X_1 = x_1, ..., X_k = x_k) = (n!/(x_1!...x_k!))p_1^x_1...p_k^x_k' },
        { name: 'Multivariate Normal Distribution', content: 'f(x) = (1/(√((2π)^k|Σ|)))e^(-1/2(x-μ)\'Σ^(-1)(x-μ))' },
        { name: 'Cauchy Distribution', content: 'f(x) = (1/π)[γ / ((x - x₀)^2 + γ^2)]' },
        { name: 'Log-Normal Distribution', content: 'f(x) = (1/(xσ√(2π)))e^(-((ln(x)-μ)^2)/(2σ^2))' },
        { name: 'Pareto Distribution', content: 'f(x) = (αx_m^α)/(x^(α+1)) for x ≥ x_m' },
        { name: 'Exponential Distribution (CDF)', content: 'F(x) = 1 - e^(-λx)' },
        { name: 'Rayleigh Distribution', content: 'f(x) = (x/σ^2)e^(-(x^2)/(2σ^2))' },
        { name: 'Gumbel Distribution', content: 'f(x) = (1/β)e^(-(x-μ)/β)e^(-e^(-(x-μ)/β))' },
        { name: 'Logistic Distribution', content: 'f(x) = e^(-(x-μ)/s) / [s(1+e^(-(x-μ)/s))^2]' },
        { name: 'Laplace Distribution', content: 'f(x) = (1/(2b))e^(-|x-μ|/b)' },
        { name: 'Maximum Likelihood Estimation', content: 'L(θ) = ∏f(x_i|θ)' },
        { name: 'Likelihood Ratio Test', content: 'λ = (L_0 / L_1)' },
        { name: 'Posterior Probability', content: 'P(θ|X) = [P(X|θ)P(θ)] / P(X)' },
        { name: 'Prior Probability', content: 'P(θ)' },
        { name: 'Predictive Distribution', content: 'P(X_new|X) = ∫P(X_new|θ)P(θ|X)dθ' },
        { name: 'Entropy', content: 'H(X) = -∑P(x)log(P(x))' },
        { name: 'Equation of a Circle', content: '(x - h)^2 + (y - k)^2 = r^2' },
        { name: 'Standard Form of a Circle', content: 'x^2 + y^2 = r^2' },
        { name: 'Diameter of a Circle', content: 'D = 2r' },
        { name: 'Circumference of a Circle', content: 'C = 2πr' },
        { name: 'Equation of an Ellipse', content: '((x - h)^2 / a^2) + ((y - k)^2 / b^2) = 1' },
        { name: 'Standard Form of an Ellipse', content: '(x^2 / a^2) + (y^2 / b^2) = 1' },
        { name: 'Foci of an Ellipse', content: 'c^2 = a^2 - b^2' },
        { name: 'Major Axis of an Ellipse', content: '2a' },
        { name: 'Minor Axis of an Ellipse', content: '2b' },
        { name: 'Eccentricity of an Ellipse', content: 'e = c / a' },
        { name: 'Area of an Ellipse', content: 'A = πab' },
        { name: 'Perimeter of an Ellipse (approximation)', content: 'P ≈ π[3(a + b) - √((3a + b)(a + 3b))]' },
        { name: 'Equation of a Parabola (Horizontal)', content: '(y - k)^2 = 4p(x - h)' },
        { name: 'Equation of a Parabola (Vertical)', content: '(x - h)^2 = 4p(y - k)' },
        { name: 'Focus of a Parabola (Horizontal)', content: '(h + p, k)' },
        { name: 'Focus of a Parabola (Vertical)', content: '(h, k + p)' },
        { name: 'Directrix of a Parabola (Horizontal)', content: 'x = h - p' },
        { name: 'Directrix of a Parabola (Vertical)', content: 'y = k - p' },
        { name: 'Latus Rectum of a Parabola', content: 'Length = 4p' },
        { name: 'Equation of a Hyperbola (Horizontal)', content: '((x - h)^2 / a^2) - ((y - k)^2 / b^2) = 1' },
        { name: 'Equation of a Hyperbola (Vertical)', content: '((y - k)^2 / a^2) - ((x - h)^2 / b^2) = 1' },
        { name: 'Foci of a Hyperbola', content: 'c^2 = a^2 + b^2' },
        { name: 'Transverse Axis of a Hyperbola', content: '2a' },
        { name: 'Conjugate Axis of a Hyperbola', content: '2b' },
        { name: 'Eccentricity of a Hyperbola', content: 'e = c / a' },
        { name: 'Asymptotes of a Hyperbola (Horizontal)', content: 'y - k = ±(b/a)(x - h)' },
        { name: 'Asymptotes of a Hyperbola (Vertical)', content: 'y - k = ±(a/b)(x - h)' },
        { name: 'Distance between Foci of a Hyperbola', content: '2c' },
        { name: 'Latus Rectum of a Hyperbola', content: 'Length = 2b^2 / a' },
        { name: 'Eccentricity of a Parabola', content: 'e = 1' },
        { name: 'Vertex of a Parabola', content: '(h, k)' },
        { name: 'Equation of a Degenerate Ellipse', content: '(x^2 / a^2) + (y^2 / b^2) = 0' },
        { name: 'Equation of a Degenerate Hyperbola', content: '(x^2 / a^2) - (y^2 / b^2) = 0' },
        { name: 'Polar Form of a Circle', content: 'r = a' },
        { name: 'Polar Form of an Ellipse', content: 'r = (ab) / √((b cos(θ))^2 + (a sin(θ))^2)' },
        { name: 'Polar Form of a Parabola', content: 'r = (l) / (1 + e cos(θ))' },
        { name: 'Polar Form of a Hyperbola', content: 'r = (l) / (1 ± e cos(θ))' },
        { name: 'Directrix of an Ellipse', content: 'x = ±a/e' },
        { name: 'Directrix of a Hyperbola', content: 'x = ±a/e' },
        { name: 'Area of a Parabolic Segment', content: 'A = (2/3)bh' },
        { name: 'Focal Length of a Parabola', content: 'Distance = 1/(4A)' },
        { name: 'Equation of an Elliptic Cone', content: '(x^2 / a^2) + (y^2 / b^2) - (z^2 / c^2) = 0' },
        { name: 'Equation of a Hyperbolic Cone', content: '(x^2 / a^2) - (y^2 / b^2) - (z^2 / c^2) = 0' },
        { name: 'Equation of an Elliptic Paraboloid', content: 'z = (x^2 / a^2) + (y^2 / b^2)' },
        { name: 'Equation of a Hyperbolic Paraboloid', content: 'z = (x^2 / a^2) - (y^2 / b^2)' },
        { name: 'Area of an Elliptic Segment', content: 'A = (π/2)abθ' },
        { name: 'Equation of a Sphere', content: '(x - h)^2 + (y - k)^2 + (z - l)^2 = r^2' },
        { name: 'Equation of a Hyperboloid of One Sheet', content: '(x^2 / a^2) + (y^2 / b^2) - (z^2 / c^2) = 1' },
        { name: 'Equation of a Hyperboloid of Two Sheets', content: '(z^2 / c^2) - (x^2 / a^2) - (y^2 / b^2) = 1' },
        { name: 'Eccentricity of a Sphere', content: 'e = 0' },
        { name: 'Standard Form of a Sphere', content: 'x^2 + y^2 + z^2 = r^2' },
        { name: 'Surface Area of a Sphere', content: 'A = 4πr^2' },
        { name: 'Volume of a Sphere', content: 'V = (4/3)πr^3' },
        { name: 'Equation of an Ellipsoid', content: '(x^2 / a^2) + (y^2 / b^2) + (z^2 / c^2) = 1' },
        { name: 'Volume of an Ellipsoid', content: 'V = (4/3)πabc' },
        { name: 'Surface Area of an Ellipsoid', content: 'A ≈ 4π[(a^p b^p + a^p c^p + b^p c^p)/3]^(1/p)' },
        { name: 'Equation of a Cylindrical Helix', content: 'r = a cos(θ), z = bθ' },
        { name: 'Equation of an Elliptic Helix', content: 'r = a cos(θ), z = cθ' },
        { name: 'Equation of a Hyperbolic Helix', content: 'r = a cosh(θ), z = cθ' },
        { name: 'Volume of a Parabolic Segment', content: 'V = (1/2)A * b * h' },
        { name: 'Area of a Circular Sector', content: 'A = (1/2)r^2θ' },
        { name: 'Perimeter of a Circular Sector', content: 'P = 2r + rθ' },
        { name: 'Area of an Annulus', content: 'A = π(R^2 - r^2)' },
        { name: 'Arc Length of an Ellipse', content: 'L ≈ π[3(a + b) - √((3a + b)(a + 3b))]' },
        { name: 'Perimeter of an Ellipse (approximation)', content: 'P ≈ π[3(a + b) - √((3a + b)(a + 3b))]' },
        { name: 'Area of a Parabolic Segment', content: 'A = (2/3)bh' },
        { name: 'Focal Length of a Parabola', content: 'Distance = 1/(4A)' },
        { name: 'Equation of an Elliptic Cone', content: '(x^2 / a^2) + (y^2 / b^2) - (z^2 / c^2) = 0' },
        { name: 'Equation of a Hyperbolic Cone', content: '(x^2 / a^2) - (y^2 / b^2) - (z^2 / c^2) = 0' },
        { name: 'Equation of an Elliptic Paraboloid', content: 'z = (x^2 / a^2) + (y^2 / b^2)' },
        { name: 'Equation of a Hyperbolic Paraboloid', content: 'z = (x^2 / a^2) - (y^2 / b^2)' },
        { name: 'Area of an Elliptic Segment', content: 'A = (π/2)abθ' },
        { name: 'Equation of a Sphere', content: '(x - h)^2 + (y - k)^2 + (z - l)^2 = r^2' },
        { name: 'Equation of a Hyperboloid of One Sheet', content: '(x^2 / a^2) + (y^2 / b^2) - (z^2 / c^2) = 1' },
        { name: 'Equation of a Hyperboloid of Two Sheets', content: '(z^2 / c^2) - (x^2 / a^2) - (y^2 / b^2) = 1' },
        { name: 'Eccentricity of a Sphere', content: 'e = 0' },
        { name: 'Standard Form of a Sphere', content: 'x^2 + y^2 + z^2 = r^2' },
        { name: 'Surface Area of a Sphere', content: 'A = 4πr^2' },
        { name: 'Volume of a Sphere', content: 'V = (4/3)πr^3' },
        { name: 'Equation of an Ellipsoid', content: '(x^2 / a^2) + (y^2 / b^2) + (z^2 / c^2) = 1' },
        { name: 'Volume of an Ellipsoid', content: 'V = (4/3)πabc' },
        { name: 'Surface Area of an Ellipsoid', content: 'A ≈ 4π[(a^p b^p + a^p c^p + b^p c^p)/3]^(1/p)' },
        { name: 'Equation of a Cylindrical Helix', content: 'r = a cos(θ), z = bθ' },
        { name: 'Equation of an Elliptic Helix', content: 'r = a cos(θ), z = cθ' },
        { name: 'Equation of a Hyperbolic Helix', content: 'r = a cosh(θ), z = cθ' },
        { name: 'Volume of a Parabolic Segment', content: 'V = (1/2)A * b * h' },
        { name: 'Area of a Circular Sector', content: 'A = (1/2)r^2θ' },
        { name: 'Perimeter of a Circular Sector', content: 'P = 2r + rθ' },
        { name: 'Area of an Annulus', content: 'A = π(R^2 - r^2)' },
        { name: 'Arc Length of a Circle', content: 'L = rθ' },
        { name: 'Area of a Sector', content: 'A = (1/2)r^2θ' },
        { name: 'Perimeter of a Sector', content: 'P = r + rθ' },
        { name: 'Area of a Segment', content: 'A = A_of_the_sector - A_of_the_triangle' },
        { name: 'Area of a Parallelogram', content: 'A = b * h' },
        { name: 'Perimeter of a Parallelogram', content: 'P = 2b + 2h' },
        { name: 'Area of a Square', content: 'A = s<sup>2</sup>' },
        { name: 'Perimeter of a Square', content: 'P = 4s' },
        { name: 'Area of a Parallelogram', content: 'A = bh' },
        { name: 'Perimeter of a Parallelogram', content: 'P = 2(l + w)' },
        { name: 'Area of a Trapezoid', content: 'A = 0.5(a + b)h' },
        { name: 'Perimeter of a Trapezoid', content: 'P = a + b + c + d' },
        { name: 'Area of an Equilateral Triangle', content: 'A = (sqrt(3)/4)s<sup>2</sup>' },
        { name: 'Perimeter of an Equilateral Triangle', content: 'P = 3s' },
        { name: 'Pythagorean Theorem', content: 'c = sqrt(a<sup>2</sup> + b<sup>2</sup>)' },
        { name: 'Perimeter of a Circle (Circumference)', content: 'C = 2πr' },
        { name: 'Volume of a Cube', content: 'V = s<sup>3</sup>' },
        { name: 'Surface Area of a Cube', content: 'A = 6s<sup>2</sup>' },
        { name: 'Volume of a Rectangular Prism', content: 'V = lwh' },
        { name: 'Surface Area of a Rectangular Prism', content: 'A = 2lw + 2lh + 2wh' },
        { name: 'Volume of a Cylinder', content: 'V = πr<sup>2</sup>h' },
        { name: 'Surface Area of a Cylinder', content: 'A = 2πrh + 2πr<sup>2</sup>' },
        { name: 'Volume of a Cone', content: 'V = (1/3)πr<sup>2</sup>h' },
        { name: 'Surface Area of a Cone', content: 'A = πr(r + s)' },
        { name: 'Volume of a Sphere', content: 'V = (4/3)πr<sup>3</sup>' },
        { name: 'Surface Area of a Sphere', content: 'A = 4πr<sup>2</sup>' },
        { name: 'Volume of a Pyramid', content: 'V = (1/3)Bh' },
        { name: 'Surface Area of a Pyramid', content: 'A = B + (1/2)Pl' },
        { name: 'Area of a Regular Polygon', content: 'A = (1/2)ap' },
        { name: 'Volume of a Tetrahedron', content: 'V = (1/6)absqrt(3)' },
        { name: 'Surface Area of a Tetrahedron', content: 'A = ab + ac + bc' },
        { name: 'Volume of a Hemisphere', content: 'V = (2/3)πr<sup>3</sup>' },
        { name: 'Surface Area of a Hemisphere', content: 'A = 2πr<sup>2</sup>' },
        { name: 'Distance Formula', content: 'd = sqrt((x<sub>2</sub> - x<sub>1</sub>)<sup>2</sup> + (y<sub>2</sub> - y<sub>1</sub>)<sup>2</sup>)' },
        { name: 'Midpoint Formula', content: 'M = ((x<sub>1</sub> + x<sub>2</sub>) / 2, (y<sub>1</sub> + y<sub>2</sub>) / 2)' },
        { name: 'Slope Formula', content: 'm = (y<sub>2</sub> - y<sub>1</sub>) / (x<sub>2</sub> - x<sub>1</sub>)' },
        { name: 'Area of a Sector', content: 'A = (1/2)r<sup>2</sup>θ' },
        { name: 'Volume of a Cuboid', content: 'V = lwh' },
        { name: 'Surface Area of a Cuboid', content: 'A = 2(lw + lh + wh)' },
        { name: 'Volume of a Triangular Prism', content: 'V = (1/2)Bh' },
        { name: 'Surface Area of a Triangular Prism', content: 'A = B + Pl' },
        { name: 'Volume of a Rectangular Pyramid', content: 'V = (1/3)lwh' },
        { name: 'Surface Area of a Rectangular Pyramid', content: 'A = lw + l√((w/2)<sup>2</sup> + h<sup>2</sup>) + w√((l/2)<sup>2</sup> + h<sup>2</sup>)' },
        { name: 'Volume of a Cylindrical Pyramid', content: 'V = (1/3)πr<sup>2</sup>h' },
        { name: 'Surface Area of a Cylindrical Pyramid', content: 'A = πr(r + l)' },
        { name: 'Volume of a Torus', content: 'V = 2π<sup>2</sup>Rr<sup>2</sup>' },
        { name: 'Surface Area of a Torus', content: 'A = 4π<sup>2</sup>Rr' },
        { name: 'Volume of a Hemisphere', content: 'V = (2/3)πr<sup>3</sup>' },
        { name: 'Surface Area of a Hemisphere', content: 'A = 2πr<sup>2</sup>' },
        { name: 'Distance Formula', content: 'd = sqrt((x2 - x1)2 + (y2 - y1)2)' },
        { name: 'Midpoint Formula', content: 'M = ((x1 + x2) / 2, (y1 + y2) / 2)' },
        { name: 'Slope Formula', content: 'm = (y2 - y1) / (x2 - x1)' },
        { name: 'Area of a Sector', content: 'A = (1/2)r<sup>2</sup>θ' },
        { name: 'Volume of a Cuboid', content: 'V = lwh' },
        { name: 'Surface Area of a Cuboid', content: 'A = 2(lw + lh + wh)' },
        { name: 'Volume of a Triangular Prism', content: 'V = (1/2)Bh' },
        { name: 'Surface Area of a Triangular Prism', content: 'A = B + Pl' },
        { name: 'Volume of a Rectangular Pyramid', content: 'V = (1/3)lwh' },
        { name: 'Surface Area of a Rectangular Pyramid', content: 'A = lw + l√((w/2)<sup>2</sup> + h<sup>2</sup>) + w√((l/2)<sup>2</sup> + h<sup>2</sup>)' },
        { name: 'Volume of a Cylindrical Pyramid', content: 'V = (1/3)πr<sup>2</sup>h' },
        { name: 'Surface Area of a Cylindrical Pyramid', content: 'A = πr(r + l)' },
        { name: 'Volume of a Torus', content: 'V = 2π<sup>2</sup>Rr<sup>2</sup>' },
        { name: 'Surface Area of a Torus', content: 'A = 4π<sup>2</sup>Rr' },
        { name: 'Volume of a Hemisphere', content: 'V = (2/3)πr<sup>3</sup>' },
        { name: 'Surface Area of a Hemisphere', content: 'A = 2πr<sup>2</sup>' },
        { name: 'Distance Formula', content: 'd = sqrt((x2 - x1)2 + (y2 - y1)2)' },
        { name: 'Midpoint Formula', content: 'M = ((x1 + x2) / 2, (y1 + y2) / 2)' },
        { name: 'Slope Formula', content: 'm = (y2 - y1) / (x2 - x1)' },
        { name: 'Area of a Sector', content: 'A = (1/2)r<sup>2</sup>θ' },
        { name: 'Volume of a Cuboid', content: 'V = lwh' },
        { name: 'Surface Area of a Cuboid', content: 'A = 2(lw + lh + wh)' },
        { name: 'Volume of a Triangular Prism', content: 'V = (1/2)Bh' },
        { name: 'Surface Area of a Triangular Prism', content: 'A = B + Pl' },
        { name: 'Volume of a Rectangular Pyramid', content: 'V = (1/3)lwh' },
        { name: 'Surface Area of a Rectangular Pyramid', content: 'A = lw + l√((w/2)<sup>2</sup> + h<sup>2</sup>) + w√((l/2)<sup>2</sup> + h<sup>2</sup>)' },
        { name: 'Surface Area of a Cylindrical Pyramid', content: 'A = πr(r + l)' },
        { name: 'Volume of a Torus', content: 'V = 2π<sup>2</sup>Rr<sup>2</sup>' },
        { name: 'Surface Area of a Torus', content: 'A = 4π<sup>2</sup>Rr' },
        { name: 'Volume of a Hemisphere', content: 'V = (2/3)πr<sup>3</sup>' },
        { name: 'Surface Area of a Hemisphere', content: 'A = 2πr<sup>2</sup>' },
        { name: 'Distance Formula', content: 'd = sqrt((x2 - x1)2 + (y2 - y1)2)' },
        { name: 'Midpoint Formula', content: 'M = ((x1 + x2) / 2, (y1 + y2) / 2)' },
        { name: 'Slope Formula', content: 'm = (y2 - y1) / (x2 - x1)' },
        { name: 'Area of a Sector', content: 'A = (1/2)r<sup>2</sup>θ' },
        { name: 'Volume of a Cuboid', content: 'V = lwh' },
        { name: 'Surface Area of a Cuboid', content: 'A = 2(lw + lh + wh)' },
        { name: 'Volume of a Triangular Prism', content: 'V = (1/2)Bh' },
        { name: 'Surface Area of a Triangular Prism', content: 'A = B + Pl' },
        { name: 'Volume of a Rectangular Pyramid', content: 'V = (1/3)lwh' },
        { name: 'Surface Area of a Rectangular Pyramid', content: 'A = lw + l√((w/2)<sup>2</sup> + h<sup>2</sup>) + w√((l/2)<sup>2</sup> + h<sup>2</sup>)' },
        { name: 'Volume of a Cylindrical Pyramid', content: 'V = (1/3)πr<sup>2</sup>h' },
        { name: 'Surface Area of a Cylindrical Pyramid', content: 'A = πr(r + l)' },
        { name: 'Volume of a Torus', content: 'V = 2π<sup>2</sup>Rr<sup>2</sup>' },
        { name: 'Surface Area of a Torus', content: 'A = 4π<sup>2</sup>Rr' },
        { name: 'Volume of a Hemisphere', content: 'V = (2/3)πr<sup>3</sup>' },
        { name: 'Surface Area of a Hemisphere', content: 'A = 2πr<sup>2</sup>' },
        { name: 'Distance Formula', content: 'd = sqrt((x2 - x1)2 + (y2 - y1)2)' },
        { name: 'Midpoint Formula', content: 'M = ((x1 + x2) / 2, (y1 + y2) / 2)' },
        { name: 'Slope Formula', content: 'm = (y2 - y1) / (x2 - x1)' },
        { name: 'Area of a Sector', content: 'A = (1/2)r<sup>2</sup>θ' },
        { name: 'Volume of a Cuboid', content: 'V = lwh' },
        { name: 'Surface Area of a Cuboid', content: 'A = 2(lw + lh + wh)' },
        { name: 'Volume of a Triangular Prism', content: 'V = (1/2)Bh' },
        { name: 'Surface Area of a Triangular Prism', content: 'A = B + Pl' },
        { name: 'Volume of a Rectangular Pyramid', content: 'V = (1/3)lwh' },
        { name: 'Surface Area of a Rectangular Pyramid', content: 'A = lw + l√((w/2)<sup>2</sup> + h<sup>2</sup>) + w√((l/2)<sup>2</sup> + h<sup>2</sup>)' },
        { name: 'Surface Area of a Cylindrical Pyramid', content: 'A = πr(r + l)' },
        { name: 'Volume of a Torus', content: 'V = 2π<sup>2</sup>Rr<sup>2</sup>' },
        { name: 'Surface Area of a Torus', content: 'A = 4π<sup>2</sup>Rr' },
        { name: 'Surface Area of a Sphere', content: 'A = 4πr<sup>2</sup>' },
        { name: 'Volume of a Sphere', content: 'V = (4/3)πr<sup>3</sup>' },
        { name: 'Surface Area of an Ellipsoid', content: 'A ≈ 4π[(a^p b^p + a^p c^p + b^p c^p)/3]^(1/p)' },
        { name: 'Volume of an Ellipsoid', content: 'V = (4/3)πabc' },
        { name: 'Surface Area of a Cone', content: 'A = πr(r + s)' },
        { name: 'Volume of a Cone', content: 'V = (1/3)πr<sup>2</sup>h' },
        { name: 'Surface Area of a Cylinder', content: 'A = 2πrh + 2πr<sup>2</sup>' },
        { name: 'Volume of a Cylinder', content: 'V = πr<sup>2</sup>h' },
        { name: 'Surface Area of a Cube', content: 'A = 6s<sup>2</sup>' },
        { name: 'Volume of a Cube', content: 'V = s<sup>3</sup>' },
        { name: 'Surface Area of a Rectangular Prism', content: 'A = 2lw + 2lh + 2wh' },
        { name: 'Volume of a Rectangular Prism', content: 'V = lwh' },
        { name: 'Surface Area of a Parallelogram', content: 'A = bh' },
        { name: 'Profit Percentage', content: 'Profit% = (Profit / Cost Price) * 100' },
        { name: 'Loss Percentage', content: 'Loss% = (Loss / Cost Price) * 100' },
        { name: 'Simple Interest', content: 'SI = (P * R * T) / 100' },
        { name: 'Amount (Simple Interest)', content: 'Amount = P + SI' },
        { name: 'Compound Interest', content: 'CI = P * (1 + (R / 100))<sup>T</sup> - P' },
        { name: 'Amount (Compound Interest)', content: 'Amount = P * (1 + (R / 100))<sup>T</sup>' },
        { name: 'Sum of First n Natural Numbers', content: 'S<sub>n</sub> = n * (n + 1) / 2' },
        { name: 'Sum of First n Odd Numbers', content: 'S<sub>n</sub> = n<sup>2</sup>' },
        { name: 'Sum of First n Even Numbers', content: 'S<sub>n</sub> = n * (n + 1)' },
        { name: 'Sum of Squares of First n Natural Numbers', content: 'S<sub>n</sub> = n * (n + 1) * (2n + 1) / 6' },
        { name: 'Sum of Cubes of First n Natural Numbers', content: 'S<sub>n</sub> = (n * (n + 1) / 2)<sup>2</sup>' },
        { name: 'nth Prime Number (Approximation)', content: 'p<sub>n</sub> ≈ n * ln(n)' },
        { name: 'Surd Simplification (Square Root)', content: '√a * √b = √(ab)' },
        { name: 'Surd Simplification (Cube Root)', content: '³√a * ³√b = ³√(ab)' },





    ]

    const formulasContainer = document.getElementById('formulas');
    const searchInput = document.getElementById('search');

    function renderFormulas(filter = '') {
        formulasContainer.innerHTML = '';
        const filteredFormulas = formulas.filter(f => f.name.toLowerCase().includes(filter.toLowerCase()));
        filteredFormulas.forEach(f => {
            const formulaElement = document.createElement('div');
            formulaElement.classList.add('formula');
            formulaElement.innerHTML = `<h2>${f.name}</h2><p>${f.content}</p>`;
            formulasContainer.appendChild(formulaElement);
        });
    }

    searchInput.addEventListener('input', (e) => {
        renderFormulas(e.target.value);
    });

    renderFormulas();
});
